POST http://localhost:3000/api/book
Content-Type: application/json

{
  "BookID": 55001,
  "Title": "Node.js Guide for Beginners",
  "ISBN": "9781234567890",
  "YearPublished": 2023,
  "Category": "Programming"
}
###

POST http://localhost:3000/api/book
Content-Type: application/json

{
  "BookID": 123,
  "Title": "Hello",
  "ISBN": "2",
  "YearPublished": 2026,
  "Category": "IT"
}

###

GET http://localhost:3000/api/book

###

PUT http://localhost:3000/api/book/123
Content-Type: application/json

{
  "BookID": 123,
  "Title": "thailand",
  "ISBN": "5",
  "YearPublished": 2007,
  "Category": "courty"
}

###

DELETE http://localhost:3000/api/book/10001

###